### ISSUE TITLE
State of the field

### ISSUE THREAD

**Issue by mfenner** [sagepublishing/rejected_article_tracker_pkg#11]
It would strengthen the paper (the quality of the writing) if the text makes clearer that rejected article tracking is only one important application of the software, where the core functionality is finding DOI records in Crossref using metadata such as title and authors.

openjournals/joss-reviews#3348

**Comment by ad48** [comment]
Thank you for the feedback. We added this paragraph to the paper after initial feedback from the other referee. Does this address your point? Happy to make further changes if not: 

> The target audience for the tracker is researchers studying rejected articles. The task performed by the tracker is 'DOI-resolution'. I.e. finding the correct Digital Object Identifier given incomplete data about a paper. So, while the intended use of the tracker is to track rejected articles, it might be used by researchers performing DOI-resolution for other reasons, such as assigning DOIs to preprints in order to connect the preprints to their published versions, e.g. [@Cabanac2021]. This is a particularly topical application at the current time due to the rapid growth of preprint servers in recent years [@Hoy2020].

**Comment by mfenner** [comment]
The comment addresses my point, thank you.  I suggest one small change: DOI resolution is in the PID community understood as looking up the URL associated with the DOI, not finding a DOI for a given set of metadata. Could you use a different term?

**Comment by ad48** [comment]
Yes, I was thinking about this already. I can see the potential for confusion. 

- I'm not sure that the 2 definitions are mutually exclusive. E.g. if we have a URL, we are checking to see if that information refers to a real DOI. The same is true in this process where we have incomplete metadata and we are checking to see if that information refers to a real DOI. This seems to fit with definitions for entity-resolution found with Google, e.g. : https://www.sciencedirect.com/topics/computer-science/entity-resolution but that doesn't mean there's no potential for confusion, which I would rather avoid. 
- If we change the terminology, I'm not sure what would be the best thing to use. In the reference you recommended, the process is called 'reference-matching', but this isn't appropriate for rejected article tracking, because we don't have 'references' as input. 

Did you have an alternative phrasing in mind? Happy to change it, just not sure what to!

**Comment by mfenner** [comment]
DOI resolution is engrained in the DOI community, that I would avoid the term used in a different context.

Maybe "DOI lookup for unstructured metadata"?

**Comment by ad48** [comment]
DOI retrieval?

**Comment by mfenner** [comment]
Sounds good.

**Comment by ad48** [comment]
Thanks again for the feedback. I've changed this to 'record-linkage' in the paper.
