### ISSUE TITLE
Paper: clarify the target audience

### ISSUE THREAD

**Issue by dhimmel** [sagepublishing/rejected_article_tracker_pkg#8]
Related to #6.

The paper mentions:

> There is little understanding of what happens to those rejected papers.

However, it's not immediately clear to me how the rejected article tracker helps with this situation. Foremost, it's not clear who has catalogs of rejected articles. The paper doesn't provide any datasets of rejected articles nor mentions any public datasets.

So I imagine the target audience of this tool is journals that have internal catalogs of rejected articles. The paper should be more explicit about the target audience that might find this tool helpful.

**Comment by ad48** [comment]
Thanks. We'll try to make this more explicit. 

- The data used in rejected article tracking is sensitive from a personal-data perspective. So, while analyses can be done and _aggregate_ data can be shared, the datasets themselves shouldn't be shared publicly. 
- The audience we had in mind were researchers working on analyses like those in the references. 
- In the time since we submitted the paper, there has been a lot of discussion about improving linking between preprints and published papers. There's quite a lot of scientometric analysis that can be done once those links are well-established. I might add something about that. 
- There is indeed a lot of application for publishing houses, but we see this as out of scope for JOSS, since it's for research software. So we didn't touch on this too much in the paper. While publishing houses would be using it for research of a kind, it seems more like a commercial/market intelligence application. That being said _editors_ of journals (irrespective of publishing house) might be interested to use the software for research on their own journals. Again - that's the same kind of analysis that we referenced in the paper. So there is some overlap there. 

Leaving issue open as a reminder until paper is updated.

**Comment by danielskatz** [comment]
in https://github.com/openjournals/joss-reviews/issues/3348

**Comment by dhimmel** [comment]
From c30b755619bf0e9517f848827911797de5e37275, the paper now states:

> The target audience for the tracker is researchers studying rejected articles, or performing DOI-resolution for other reasons, such as assigning DOIs to preprints in order to connect the preprints to their published versions.
